name: Core
main: us.corenetwork.core.CorePlugin
version: 1.0.0
depend: [GriefPrevention]
author: matejdro
commands:
    core:
        description: Main command
    chp:
    checkpoint:
    rspawn:
        description: Spawn randomly in the world
    rspawnteam:
        description: Add Remove from respawn team
    togglespawn:
        description: Disable spawning closer to biggest claim
    unprotect:
        description: Disable invincibility upon spawn
    warp:
        description: Warps
    sudo:
        description: sudo
    tp:
        description: tp
    bring:
        description: bring    
    swap:
        dscription: swap
    calc:
        description: Calculator
    trapped:
        description: Rescue from trap
    clear:
        description: Clear player inventory
    vanish:
        description: Vanish player
    unvanish:
        description: Unvanish player
    effect:
        description: Custom effect command
    enchant:
        description: Custom enchant command 
    god:
        description: God mode
    ungod:
        description: Revoke God mode
    gamemode:
        description: Revoke God mode
        aliases: gm
    kit:
        description: Kit package for a player.